stages:
    - test

test:alpine:
    image: alpine
    stage: test
    script:
        - apk update
        - apk add abuild coreutils gcc git linux-headers lua5.3-dev make musl-dev openssl-dev scdoc linux-headers zlib-dev
        - make install
        - mkdir /root/.abuild/
        - abuild-keygen -n 2>&1 | grep "PACKAGER_PRIVKEY" | sed 's/>>> //' > /root/.abuild/abuild.conf
        - make -j$(nproc) check
    tags:
        - docker-alpine

test:debian:
    image: debian
    stage: test
    script:
        - apt-get update
        - apt-get install -y make gcc git libssl-dev zlib1g-dev lua5.3-dev sudo
        - git clone https://git.sr.ht/~sircmpwn/scdoc
        - (cd scdoc && make && make install)
        - git clone https://gitlab.alpinelinux.org/alpine/abuild.git
        - (cd abuild && make install)
        - unlink /bin/sh
        - ln -s /bin/bash /bin/sh
        - echo "begin install"
        - make install
        - echo "install complete"
        - mkdir /root/.abuild/
        - abuild-keygen -n 2>&1 | grep "PACKAGER_PRIVKEY" | sed 's/>>> //' > /root/.abuild/abuild.conf
        - make -j$(nproc) check
    tags:
        - docker-alpine
        - x86_64
