stages:
    - test

test:alpine:
    image: alpine
    stage: test
    script:
        - apk update
        - apk add make gcc git musl-dev openssl-dev linux-headers zlib-dev lua5.3-dev lua5.3-lzlib libretls-dev
        - make -j$(nproc) check
    tags:
        - docker-alpine
        - x86_64

test-meson:alpine:
    image: alpine
    stage: test
    script:
        - apk update
        - apk add make gcc git musl-dev openssl-dev linux-headers zlib-dev lua5.3-dev lua5.3-lzlib meson zlib-static openssl-libs-static libretls-dev
        - meson build
        - ninja -C build
    tags:
        - docker-alpine
        - x86_64

test:debian:
    image: debian
    stage: test
    script:
        - apt-get update
        - apt-get install -y make gcc git libssl-dev zlib1g-dev lua5.3-dev lua5.2 lua-zlib-dev sudo
        - unlink /bin/sh
        - ln -s /bin/bash /bin/sh
        - make -j$(nproc) check
    tags:
        - docker-alpine
        - x86_64
